# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainWindow.ui'
#
# Created by: PySide UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_primvarManager(object):
    def setupUi(self, primvarManager):
        primvarManager.setObjectName(_fromUtf8("primvarManager"))
        primvarManager.resize(550, 800)
        self.centralwidget = QtGui.QWidget(primvarManager)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.mainLayout = QtGui.QVBoxLayout(self.centralwidget)
        # self.mainLayout.setMargin(0)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName(_fromUtf8("mainLayout"))
        self.logo = QtGui.QLabel(self.centralwidget)
        self.logo.setMinimumSize(QtCore.QSize(0, 50))
        self.logo.setText(_fromUtf8(""))
        self.logo.setObjectName(_fromUtf8("logo"))
        self.mainLayout.addWidget(self.logo)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setIconSize(QtCore.QSize(32, 32))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.create = QtGui.QWidget()
        self.create.setObjectName(_fromUtf8("create"))
        self.verticalLayout = QtGui.QVBoxLayout(self.create)
        # self.verticalLayout.setMargin(1)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.toolBox = QtGui.QToolBox(self.create)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.rmanc = QtGui.QWidget()
        self.rmanc.setGeometry(QtCore.QRect(0, 0, 532, 432))
        self.rmanc.setObjectName(_fromUtf8("rmanc"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.rmanc)
        # self.verticalLayout_2.setMargin(1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.createRmanC = QtGui.QPushButton(self.rmanc)
        self.createRmanC.setMinimumSize(QtCore.QSize(0, 0))
        self.createRmanC.setMaximumSize(QtCore.QSize(100, 16777215))
        self.createRmanC.setIconSize(QtCore.QSize(18, 18))
        self.createRmanC.setObjectName(_fromUtf8("createRmanC"))
        self.verticalLayout_2.addWidget(self.createRmanC)
        self.scrollArea = QtGui.QScrollArea(self.rmanc)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 518, 391))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.rmanCLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        # self.rmanCLayout.setMargin(1)
        self.rmanCLayout.setObjectName(_fromUtf8("rmanCLayout"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.toolBox.addItem(self.rmanc, _fromUtf8(""))
        self.rmanf = QtGui.QWidget()
        self.rmanf.setGeometry(QtCore.QRect(0, 0, 532, 432))
        self.rmanf.setObjectName(_fromUtf8("rmanf"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.rmanf)
        # self.verticalLayout_3.setMargin(1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.createRmanF = QtGui.QPushButton(self.rmanf)
        self.createRmanF.setMaximumSize(QtCore.QSize(100, 16777215))
        self.createRmanF.setIconSize(QtCore.QSize(18, 18))
        self.createRmanF.setObjectName(_fromUtf8("createRmanF"))
        self.verticalLayout_3.addWidget(self.createRmanF)
        self.scrollArea_2 = QtGui.QScrollArea(self.rmanf)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 518, 391))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.rmanFLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        # self.rmanFLayout.setMargin(1)
        self.rmanFLayout.setObjectName(_fromUtf8("rmanFLayout"))
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.scrollArea_2)
        self.toolBox.addItem(self.rmanf, _fromUtf8(""))
        self.rmann = QtGui.QWidget()
        self.rmann.setGeometry(QtCore.QRect(0, 0, 532, 432))
        self.rmann.setObjectName(_fromUtf8("rmann"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.rmann)
        # self.verticalLayout_4.setMargin(1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.createRmanN = QtGui.QPushButton(self.rmann)
        self.createRmanN.setMaximumSize(QtCore.QSize(100, 16777215))
        self.createRmanN.setIconSize(QtCore.QSize(18, 18))
        self.createRmanN.setObjectName(_fromUtf8("createRmanN"))
        self.verticalLayout_4.addWidget(self.createRmanN)
        self.scrollArea_3 = QtGui.QScrollArea(self.rmann)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName(_fromUtf8("scrollArea_3"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 518, 391))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.rmanNLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_3)
        # self.rmanNLayout.setMargin(1)
        self.rmanNLayout.setObjectName(_fromUtf8("rmanNLayout"))
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_4.addWidget(self.scrollArea_3)
        self.toolBox.addItem(self.rmann, _fromUtf8(""))
        self.rmanp = QtGui.QWidget()
        self.rmanp.setGeometry(QtCore.QRect(0, 0, 532, 432))
        self.rmanp.setObjectName(_fromUtf8("rmanp"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.rmanp)
        # self.verticalLayout_5.setMargin(1)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.createRmanP = QtGui.QPushButton(self.rmanp)
        self.createRmanP.setMaximumSize(QtCore.QSize(100, 16777215))
        self.createRmanP.setIconSize(QtCore.QSize(18, 18))
        self.createRmanP.setObjectName(_fromUtf8("createRmanP"))
        self.verticalLayout_5.addWidget(self.createRmanP)
        self.scrollArea_4 = QtGui.QScrollArea(self.rmanp)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName(_fromUtf8("scrollArea_4"))
        self.scrollAreaWidgetContents_4 = QtGui.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 518, 391))
        self.scrollAreaWidgetContents_4.setObjectName(_fromUtf8("scrollAreaWidgetContents_4"))
        self.rmanPLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_4)
        # self.rmanPLayout.setMargin(1)
        self.rmanPLayout.setObjectName(_fromUtf8("rmanPLayout"))
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_5.addWidget(self.scrollArea_4)
        self.toolBox.addItem(self.rmanp, _fromUtf8(""))
        self.rmans = QtGui.QWidget()
        self.rmans.setGeometry(QtCore.QRect(0, 0, 532, 432))
        self.rmans.setObjectName(_fromUtf8("rmans"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.rmans)
        # self.verticalLayout_6.setMargin(1)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.createRmanS = QtGui.QPushButton(self.rmans)
        self.createRmanS.setMaximumSize(QtCore.QSize(100, 16777215))
        self.createRmanS.setIconSize(QtCore.QSize(18, 18))
        self.createRmanS.setObjectName(_fromUtf8("createRmanS"))
        self.verticalLayout_6.addWidget(self.createRmanS)
        self.scrollArea_5 = QtGui.QScrollArea(self.rmans)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName(_fromUtf8("scrollArea_5"))
        self.scrollAreaWidgetContents_5 = QtGui.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 518, 391))
        self.scrollAreaWidgetContents_5.setObjectName(_fromUtf8("scrollAreaWidgetContents_5"))
        self.rmanSLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_5)
        # self.rmanSLayout.setMargin(1)
        self.rmanSLayout.setObjectName(_fromUtf8("rmanSLayout"))
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayout_6.addWidget(self.scrollArea_5)
        self.toolBox.addItem(self.rmans, _fromUtf8(""))
        self.rmanv = QtGui.QWidget()
        self.rmanv.setGeometry(QtCore.QRect(0, 0, 532, 432))
        self.rmanv.setObjectName(_fromUtf8("rmanv"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.rmanv)
        # self.verticalLayout_7.setMargin(1)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.createRmanV = QtGui.QPushButton(self.rmanv)
        self.createRmanV.setMaximumSize(QtCore.QSize(100, 16777215))
        self.createRmanV.setIconSize(QtCore.QSize(18, 18))
        self.createRmanV.setObjectName(_fromUtf8("createRmanV"))
        self.verticalLayout_7.addWidget(self.createRmanV)
        self.scrollArea_6 = QtGui.QScrollArea(self.rmanv)
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName(_fromUtf8("scrollArea_6"))
        self.scrollAreaWidgetContents_6 = QtGui.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 518, 391))
        self.scrollAreaWidgetContents_6.setObjectName(_fromUtf8("scrollAreaWidgetContents_6"))
        self.rmanVLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_6)
        # self.rmanVLayout.setMargin(1)
        self.rmanVLayout.setObjectName(_fromUtf8("rmanVLayout"))
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_6)
        self.verticalLayout_7.addWidget(self.scrollArea_6)
        self.toolBox.addItem(self.rmanv, _fromUtf8(""))
        self.verticalLayout.addWidget(self.toolBox)
        self.assign = QtGui.QPushButton(self.create)
        self.assign.setMinimumSize(QtCore.QSize(0, 40))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/apply")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.assign.setIcon(icon)
        self.assign.setIconSize(QtCore.QSize(32, 32))
        self.assign.setObjectName(_fromUtf8("assign"))
        self.verticalLayout.addWidget(self.assign)
        self.tabWidget.addTab(self.create, _fromUtf8(""))
        self.edit = QtGui.QWidget()
        self.edit.setObjectName(_fromUtf8("edit"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.edit)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label = QtGui.QLabel(self.edit)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_9.addWidget(self.label)
        self.tabWidget.addTab(self.edit, _fromUtf8(""))
        self.mainLayout.addWidget(self.tabWidget)
        primvarManager.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(primvarManager)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFIle = QtGui.QMenu(self.menubar)
        self.menuFIle.setObjectName(_fromUtf8("menuFIle"))
        self.menuHelp = QtGui.QMenu(self.menuFIle)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuEmail_Developer = QtGui.QMenu(self.menuFIle)
        self.menuEmail_Developer.setObjectName(_fromUtf8("menuEmail_Developer"))
        primvarManager.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(primvarManager)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        primvarManager.setStatusBar(self.statusbar)
        self.action_pxar_Documenation = QtGui.QAction(primvarManager)
        self.action_pxar_Documenation.setObjectName(_fromUtf8("action_pxar_Documenation"))
        self.action_clear = QtGui.QAction(primvarManager)
        self.action_clear.setObjectName(_fromUtf8("action_clear"))
        self.action_email_suggestion = QtGui.QAction(primvarManager)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/suggestions")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_email_suggestion.setIcon(icon1)
        self.action_email_suggestion.setObjectName(_fromUtf8("action_email_suggestion"))
        self.action_email_error = QtGui.QAction(primvarManager)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/error")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_email_error.setIcon(icon2)
        self.action_email_error.setObjectName(_fromUtf8("action_email_error"))
        self.actionExit = QtGui.QAction(primvarManager)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.action_tool_Documentation = QtGui.QAction(primvarManager)
        self.action_tool_Documentation.setObjectName(_fromUtf8("action_tool_Documentation"))
        self.action_close_ui = QtGui.QAction(primvarManager)
        self.action_close_ui.setObjectName(_fromUtf8("action_close_ui"))
        self.menuHelp.addAction(self.action_pxar_Documenation)
        self.menuHelp.addAction(self.action_tool_Documentation)
        self.menuEmail_Developer.addAction(self.action_email_suggestion)
        self.menuEmail_Developer.addAction(self.action_email_error)
        self.menuFIle.addAction(self.menuHelp.menuAction())
        self.menuFIle.addAction(self.action_clear)
        self.menuFIle.addAction(self.menuEmail_Developer.menuAction())
        self.menuFIle.addSeparator()
        self.menuFIle.addAction(self.action_close_ui)
        self.menubar.addAction(self.menuFIle.menuAction())

        self.retranslateUi(primvarManager)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(primvarManager)

    def retranslateUi(self, primvarManager):
        primvarManager.setWindowTitle(_translate("primvarManager", "PrimVar Manager", None))
        self.createRmanC.setText(_translate("primvarManager", "Create", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.rmanc), _translate("primvarManager", "rmanC", None))
        self.createRmanF.setText(_translate("primvarManager", "Create", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.rmanf), _translate("primvarManager", "rmanF", None))
        self.createRmanN.setText(_translate("primvarManager", "Create", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.rmann), _translate("primvarManager", "rmanN", None))
        self.createRmanP.setText(_translate("primvarManager", "Create", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.rmanp), _translate("primvarManager", "rmanP", None))
        self.createRmanS.setText(_translate("primvarManager", "Create", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.rmans), _translate("primvarManager", "rmanS", None))
        self.createRmanV.setText(_translate("primvarManager", "Create", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.rmanv), _translate("primvarManager", "rmanV", None))
        self.assign.setText(_translate("primvarManager", "Assign", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.create), _translate("primvarManager", "Create", None))
        self.label.setText(_translate("primvarManager", "Coming Soon", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.edit), _translate("primvarManager", "Edit", None))
        self.menuFIle.setTitle(_translate("primvarManager", "FIle", None))
        self.menuHelp.setTitle(_translate("primvarManager", "Help", None))
        self.menuEmail_Developer.setTitle(_translate("primvarManager", "Email Developer", None))
        self.action_pxar_Documenation.setText(_translate("primvarManager", "Pixar Documenation", None))
        self.action_clear.setText(_translate("primvarManager", "Clear", None))
        self.action_email_suggestion.setText(_translate("primvarManager", "Sugestions", None))
        self.action_email_error.setText(_translate("primvarManager", "Error/Issues", None))
        self.actionExit.setText(_translate("primvarManager", "Exit", None))
        self.action_tool_Documentation.setText(_translate("primvarManager", "Tool Documentation", None))
        self.action_close_ui.setText(_translate("primvarManager", "Close", None))

from .images import images_rc
